# GitHub Pages Configuration

This repository is configured for GitHub Pages deployment.

## Deployment

1. Push code to main branch
2. Go to repository Settings > Pages
3. Select "Deploy from a branch"
4. Choose "main" branch and "/ (root)" folder
5. Save settings

The site will be available at: `https://<username>.github.io/<repository-name>`

## File Structure for GitHub Pages

- `index.html` - Main page (served as root)
- `order.html` - Order page
- `payment.html` - Payment page
- `static/` - Static assets (CSS, JS, images)

## Notes

- All paths are relative for GitHub Pages compatibility
- No server-side processing required
- Uses localStorage for data persistence
- Fully client-side application
